require_relative 'sudoku/parser'
require_relative 'sudoku/puzzle'
require_relative 'sudoku/support'
require_relative 'sudoku/solver'
require_relative 'sudoku/strategies/base_strategy'
require_relative 'sudoku/strategies/uniq_for_tile'
